spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

job:
  timeZone: ${JOB_TIME_ZONE:Europe/Kiev}

telegram:
  externalUrl: ${EXTERNAL_URL:https://c9c4-194-44-46-60.eu.ngrok.io}
  internalUrl: ${INTERNAL_URL:http://localhost:80}
